### ISSUE TITLE
Radiotap header corruption using libtins v3.4 and v3.5

### ISSUE THREAD

**Issue by Mister-X-** [mfontanini/libtins#218] opened 2017-06-01 16:18 UTC
When using the following simple example to read one packet and write it to file, the radiotap header gets corrupted (the rest of the packet looks fine). It also happens when reading a pcap file:

```
#include <tins/packet_writer.h>
#include <tins/pdu.h>
#include <tins/data_link_type.h>
#include <tins/radiotap.h>
#include <iostream>
#include <stdio.h>

// g++ -o radiotap_parse_bug radiotap_parse_bug.cpp -ltins

using namespace Tins;
using namespace std;


int main(int argc, char* argv[]) {
	if(argc != 2) {
		cout << "Usage: " <<* argv << " <DEVICE/FILE>" << endl;
		return EXIT_FAILURE;
	}
	BaseSniffer * sniffer = NULL;

	// Check if it's a file
	FILE * f = fopen(argv[1], "r");

	if (f == NULL) {
		sniffer = new Sniffer(argv[1]);
	} else {
		fclose(f);
		sniffer = new FileSniffer(argv[1]);
	}

	// Check DL
The rest of the packet (after the radiotap header) looks fine.T and sniff one packet
	cout << "DLT: " << sniffer->link_type() << endl;
    PDU * pdu = sniffer->next_packet();

	// Write to file
	PacketWriter pw("1packet.pcap", DataLinkType<RadioTap>());
	pw.write(pdu);

	// Free resources
	delete pdu;
	delete sniffer;

	return EXIT_SUCCESS;
}
```

System used: Ubuntu 16.04.2 Desktop with kernel 4.8.0-51-generic (64 bit).

I don't remember exactly how I compiled v3.5 (it shouldn't matter since the bug is in both versions) but for v3.4, I just compiled it with C++11:
```
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting build type to 'RelWithDebInfo' as none was specified.
-- Build will generate a shared library. Use LIBTINS_BUILD_SHARED=0 to perform a static build
-- Found PCAP: /usr/lib/x86_64-linux-gnu/libpcap.so  
-- Performing Test PCAP_LINKS_SOLO
-- Performing Test PCAP_LINKS_SOLO - Success
-- Looking for pcap_get_pfring_id
-- Looking for pcap_get_pfring_id - not found
-- Looking for pcap_set_immediate_mode
-- Looking for pcap_set_immediate_mode - found
-- Performing Test _HAS_CXX11_FLAG
-- Performing Test _HAS_CXX11_FLAG - Success
-- Checking C++ support for "decltype"
-- Checking C++ support for "decltype": works
-- Checking C++ support for "declval"
-- Checking C++ support for "declval": works
-- Checking C++ support for "initializer_list"
-- Checking C++ support for "initializer_list": works
-- Checking C++ support for "rvalue-references"
-- Checking C++ support for "rvalue-references": works
-- Checking C++ support for "functional"
-- Checking C++ support for "functional": works
-- Checking C++ support for "chrono"
-- Checking C++ support for "chrono": works
-- Checking C++ support for "builtin-swap"
-- Checking C++ support for "builtin-swap": works
-- Enabling C++11 features
-- Enabling IEEE 802.11 support.
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.0.2g") 
-- Enabling WPA2 decryption support.
-- Boost version: 1.58.0
-- Enabling TCP ACK tracking support.
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   regex
-- googletest git submodule is absent. Run `git submodule init && git submodule update` to get it
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/Downloads/libtins-3.4/build
```

Here are both pcaps (the one that starts with libtins was the one captured with the program above and the other one is the exact same packet captured with tcpdump running at the same time). Since github doesn't allow pcap or tar.gz, here is a link to them: https://ufile.io/zlfiy

**Comment by mfontanini** [comment] 2017-06-01 16:26
This is a great coincidence, because I've just finished re-writing RadioTap parsing almost from scratch and the new version works fine. You can find this code in the `develop` branch. I'll push it to `master` once I'm fully confident as I've been changing a lot of stuff.

**Comment by Mister-X-** [comment] 2017-06-01 17:39
Awesome. Feel free to keep the pcap for unit tests.

So I guess you can close the bug now (or maybe you want to wait until pushed to master).

**Comment by mfontanini** [comment] 2017-06-01 17:41
Mow this actually can't really fail, as all of the input options are stored in a buffer which is not modified at all between parsing/serializing, so it should be impossible to corrupt the packet. I'll probably add the packet as part of a unit test just in case though.

I'll probably push this to master over the weekend, we can close it then. Thanks for the report including the pcap files and code by the way!

**Comment by Mister-X-** [comment] 2017-06-01 17:51
You can also do whatever you want with the code (and put whatever license on it) if that's any useful for anybody else or in the examples.

**Comment by mfontanini** [comment] 2017-06-01 17:58
I meant the code for testing and issue reproducing purposes. Most issues that show up here don't provide any code nor pcap files so it's good to see one having both of them :)

**Closed** 2017-06-06 21:54 UTC
