### ISSUE TITLE
Corruption and crashes when using IP options

### ISSUE THREAD

**Issue by thrimbor** [mfontanini/libtins#288] opened 2018-04-08 05:05 UTC
When handling pcap files which contain IP packets with options, libtins either crashes (observed when using EOL or NOP) or corrupts the packet. In the minimal example provided [here](https://nextcloud.improved-madness.de/index.php/s/YmQ9zg8oe3XCiYj), libtins overwrites the first byte of the contained UDP-header with a zero, changing the port-number.

I observed this behavior on Arch Linux with libtins 4.0. Version 3.4 on Ubuntu 17.10 seems to be fine instead.

**Comment by mfontanini** [comment] 2018-04-08 05:36
Ugh this sucks, sorry. I know what the issue is, I'll fix it tomorrow and I'll run this with randomized inputs to make sure it doesn't blow up. Thanks for the report!

**Comment by mfontanini** [comment] 2018-04-08 15:14
Just pushed a fix to `develop`. I'll merge it to master in about an hour.

**Closed** 2018-04-08 16:15 UTC

**Comment by thrimbor** [comment] 2018-04-08 16:28
That was quick, thanks!

**Comment by pepper-jk** [comment] 2018-12-10 14:55
Could we get a new release including this fix?

**Comment by mfontanini** [comment] 2018-12-10 17:24
That's probably a good idea, I'll try to release this tonight.

**Comment by mfontanini** [comment] 2018-12-11 02:14
Just pushed [the new tag](https://github.com/mfontanini/libtins/releases/tag/v4.1)

**Comment by pepper-jk** [comment] 2018-12-12 13:01
Thanks for the fast reply.
