### ISSUE TITLE
tins.dll exports nothing

### ISSUE THREAD

**Issue by gvanem** [mfontanini/libtins#120] opened 2015-12-26 15:03 UTC
I'm a neophyte when it comes to Cmake. But I used this command to configure and build a `tins.dll`:
```
md build & cd build
set OPT=-DLIBTINS_ENABLE_WPA2=0  ^
        -DLIBTINS_BUILD_SHARED=1 ^
        -DLIBTINS_ENABLE_CXX11=1 ^
        -DPCAP_ROOT_DIR=..

cmake -G "NMake Makefiles" %OPT% ..
```

(all in a little .bat-file). But after a `nmake tins`, I can see `tins.dll` exports exactly 0 functions!? How is that supposed to be used?

From the above `cmake`:
```
-- Using specified 'Debug' build type.
-- Build will generate a shared library. Use LIBTINS_BUILD_SHARED=0 to perform a static build
```
`'Debug'` seems to be default. Although `CmakeLists.txt`  says ` Compile in release mode by default`.
 I didn't specify it AFAICS. I want `Release`, but how?

**Comment by mfontanini** [comment] 2015-12-26 15:37
I've always generated static librarys (using ```LIBTINS_BUILD_SHARED=0```). I've never generated dlls using cmake either. I'll have a look at that.

If you want to change the build type, use ```cmake -DCMAKE_BUILD_TYPE=RELEASE```.

**Comment by gvanem** [comment] 2015-12-26 16:05
>  use cmake -DCMAKE_BUILD_TYPE=RELEASE.

Thanks, that gave a `tins.dll` w/o any dependencies on any debug DLLs.
But the export issue remains. AFAICS, there *must* be a `include/tins/api.h`with something like this:
```  
#if defined(_WIN32) && !defined(LIBTINS_STATIC)
  #if defined(BUILDING_LIBTINS)
    #define LIBTINS_API __declspec(dllexport)
  #else
    #define LIBTINS_API __declspec(dllexport)
  #endif
#else
  #define LIBTINS_API
#endif
```
And included in every other .h-file. Here I've put that in my generated `include/tins/config.h`, added the `LIBTINS_API` to the classes in `sniffer.h` and now I see that those functions gets exported.

**Comment by mfontanini** [comment] 2015-12-26 16:18
Oh cool, I wasn't aware of that. I'll add that later.

Thanks!

**Comment by mfontanini** [comment] 2015-12-28 14:49
I just pushed a fix for this to the develop branch. I'd really appreciate if you could have a look :). 

I made some tests and it seems to work as expected. If you build using LIBTINS_BUILD_SHARED=0, no declspec attribute should be set on classes now.

**Comment by gvanem** [comment] 2015-12-28 16:03
I haven't tried it, but by reading the diffs, I have some comments. In:
```
+    // If libtins was built into a shared library
+    #if !defined(TINS_STATIC_BUILD)
```
IMHO, this should be `TINS_STATIC`. I.e. it can be a static build or *usage* case.
```
+        // Export/import symbols, depending on whether we're compiling or consuming the lib
+        #ifdef tins_EXPORTS
+            #define TINS_API __declspec(dllexport)
+        #else
+            #define TINS_API __declspec(dllimport)
+        #endif // tins_EXPORTS
+    #else // TINS_STATIC_BUILD
+        // Otherwise, default this to an empty macro
+        #define TINS_API
+    #endif // TINS_STATIC_BUILD
```
And what about other Windows static/dynamic targets? MingW etc. I think you should lift the API-stuff into a `_WIN32` section.

And BTW, putting a function marked as `__declspec(dllexport)` into a static lib works fine. It seems both `ar` and `lib` ignores those attributes in that case. Ref the latest export/import change 
to libpcap:  https://github.com/the-tcpdump-group/libpcap/blob/master/pcap/export-defs.h

**Comment by mfontanini** [comment] 2015-12-28 16:36
Thanks for your feedback! 

```IMHO, this should be TINS_STATIC. I.e. it can be a static build or usage case.```

I'm exporting this into the ```config.h``` header that CMake generates, so that macro will be defined for that build. There should be no need for users to define anything when building their own projects and linking to a static build of libtins; that flag is persistent for the whole build.

You're right about wrapping that around a check for _WIN32 rather than VS.

As for ```tins_EXPORTS```, that macro name is automatically generated by CMake (based on the library name). That name shouldn't collide with other user-defined names, so I guess it's fine.

Finally, regarding the ```dllexport``` attribute even when building a static lib, I ended up doing it this way after doing some tests. Even if I built a library statically and tried to link directly against the .lib, if I defined ```dllexport``` for any classes, it kept trying to look for the dll file, even if it wasn't there.

**Comment by gvanem** [comment] 2015-12-28 16:53
>  There should be no need for users to define anything when building their own projects and linking to 
> a static build of libtins; 

I don't quite follow you? Those users (using `tins.lib` / `libtins.a` in a foreign app.) *must* define `TINS_STATIC`. No?

>  it kept trying to look for the dll file, even if it wasn't there.

You probably used gcc and `-ltins`? Try an explicit lib-name.

**Comment by mfontanini** [comment] 2015-12-28 16:56
> I don't quite follow you? Those users (using tins.lib / libtins.a in a foreign app.) must define TINS_STATIC. No?

When you build libtins, a `config.h` file is generated that's included by all files in the project. What I did is to add that macro (`TINS_STATIC_BUILD`) into that config file. This means the library will know while being built and while being included by another project, that the libtins build was done statically. So users don't need to define that macro, since it will be already defined by the `config.h` file.

> You probably used gcc and -ltins? Try an explicit lib-name.

No, I used VS and was linking against the full path of the .lib file (e.g. C:\foo.lib).

**Comment by gvanem** [comment] 2015-12-28 18:00
>  So users don't need to define that macro, since it will be already defined by the config.h file.

Meaning you'll have to run Cmake again before switching static/shared? If so, :-1: .

> No, I used VS and was linking against the full path of the .lib file (e.g. C:\foo.lib).

Try to look at the pre-processed output in that case. It doesn't look to be correct.

**Comment by mfontanini** [comment] 2015-12-28 18:03
> Meaning you'll have to run Cmake again before switching static/shared? If so, :-1: .

I hadn't thought about people building the project through something that's not cmake. I always configure and build through cmake and make, so that made sense to me. In that case, I'll remove it and have users define TINS_STATIC when using it.

I'll have a look at the other thing later. 

Thanks!

**Comment by gvanem** [comment] 2015-12-28 18:28
>  I always configure and build through cmake and make ..

I really know little about Cmake, but enough to hate it;really ugly syntax and obfuscated makefiles so I cannot tell what it's really trying to do. I prefer GNU-make (from `make -n` it's pretty clear what it's trying to build and how). 

BTW. I'm not sure if you intend that libtins needs to be installed (`make install`) before using it in a foreign app. I wonder since the `-I`-path(s) looks a bit funny. E.g. in `example/traceroute.cpp` there is:
```
#include <tins/tins.h>
```
But `tins.h` has things like:
```
#include "dns.h"
...
```
Meaning a foreign makefile (assuming an *in-place* build), needs to have both:
```
  CFLAGS = -I<libtins-root>/include -I<libtins-root>/include/tins
```

Was that your intention? Or should `  CFLAGS = -I<libtins-root>/include`be enough?

**Comment by mfontanini** [comment] 2015-12-29 12:30
Those include directives are going to be relative to the file `tins.h`, so `-I<libtins-root>/include` will be enough. I've used libtins on Windows in the past without installing the library anywhere by doing this.

**Comment by mfontanini** [comment] 2015-12-29 16:47
Okay, so using dllexport doesn't work if you're building a static lib. pcap does that because it probably doesn't allow you to build a static lib on Windows. Every project I find online checks for `<SOMETHING>_STATIC`, so I guess there's a reason for that.

**Closed** 2016-02-01 05:18 UTC
Labels: fixed-on-develop

**Comment by Ohmnivore** [comment] 2016-03-05 01:05
I'm confused. Can we compile .dlls? Just tried and it came out nearly empty. The docs still hint at `-DLIBTINS_BUILD_SHARED=1` so I wonder if it's just a problem with my build environment or whatever.

**Comment by mfontanini** [comment] 2016-03-10 21:00
Sorry, I saw this and then forgot to reply. That's supposed to work. Are you using VC?

**Comment by Ohmnivore** [comment] 2016-03-10 21:03
No worries. I was using CMake 3.2.3 and VS 2013.

**Comment by mfontanini** [comment] 2016-03-10 21:22
I tried it and I get a 1.9MB dll file so it looks like there's stuff in there. I loaded the dll with dependency walker and I see what looks like all member functions being exported, so that looks okay for me.

**Comment by Ohmnivore** [comment] 2016-03-10 21:53
Wow just tried again and it works now. Debug dll is 1.9 MB too. I can't explain why. Maybe because I rebooted the computer since then or something.

**Comment by vfdev-5** [comment] 2017-05-19 12:41
Hi, 
There is another detail missing on Windows during installation phase of dll. For example, when I run 
```
nmake install 
```
I got `include` and `lib` folders with headers and `tins.lib` without `tins.dll`. The latter can be added with 
```
IF(WIN32)
    install(TARGETS tins RUNTIME DESTINATION bin)
ENDIF(WIN32)
```
in `CMakeLists.txt` in `src` folder.

Another point I do not understand with `libtins` is how `libpcap` dependency is supposed to be handled. I mean, if I want to create an application using libtins with CMake, I would do something like 
```
find_package(libtins REQUIRED)
include_directories(${LIBTINS_INCLUDE_DIRS})
link_libraries(${LIBTINS_LIBRARIES})
```
However, the headers of `libtins` include directly `pcap.h`. Probably, it could be good to export your custom `FindPCAP.cmake` module in `libtins` installation, to simplify the things?

Cheers,
PS. Thanks for your project, really helpful !

**Comment by mfontanini** [comment] 2017-05-19 16:05
Why would you want the destination to be `bin` for `tins.dll`? Shouldn't it be in `lib` as well considering it's actually a library?

Regarding finding libpcap when including libtins, I think if you define `PCAP_ROOT_DIR` before calling `find_package` for libtins it should find it.

**Comment by vfdev-5** [comment] 2017-05-19 16:16
About `bin` it can be a convention that if you ship some apps or examples, then necessary `dll`s are just near them to allow no problem execution (missing dlls etc).

When I include `libtins` I get the following error : 
```
CMakeLists.txt:23: error : By not providing "FindPCAP.cmake" in CMAKE_MODULE_PATH this project has asked CMake to find a package configuration file provided by "PCAP", but CMake did not find one. Could not find a package configuration file provided by "PCAP" with any of the following names: PCAPConfig.cmake pcap-config.cmake Add the installation prefix of "PCAP" to CMAKE_PREFIX_PATH or set "PCAP_DIR" to a directory containing one of the above files.  If "PCAP" provides a separate development package or SDK, be sure it has been installed.
```
which is OK because I did not specified `FindPCAP.cmake`. The problem is that `FindPCAP.cmake` is located in the libtins sources and not in the installation folder.

**Comment by mfontanini** [comment] 2017-05-19 17:55
Ah okay, I wasn't aware of how Windows ships stuff. If you want to create a PR for that, that would be great.

Regarding the CMake error, that would happen if you include it via `add_subdirectory`, right? Otherwise you'd be bypassing libtins' CMakeLists.txt alltogether. I'll test this and see what I can do about it.

**Comment by vfdev-5** [comment] 2017-05-22 07:45
Concerning a PR, I think there could be some other stuff to check on Windows related to `static` or `dynamic` option. I'll check it and submit you a PR. 

Regarding the CMake error, here is the way I'm using `libtins` in my application:

**CMakeLists.txt**
```
project(SocketListener)
cmake_minimum_required(VERSION 3.0)

# Use C++11
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++1y")

# Use Boost.ASIO
set(Boost_USE_STATIC_LIBS ON)
set(Boost_USE_MULTITHREADED ON)
add_definitions( -DBOOST_ALL_NO_LIB )
find_package(Boost 1.64.0 COMPONENTS system regex REQUIRED)
include_directories(${Boost_INCLUDE_DIR})
link_libraries(${Boost_LIBRARIES})

# Use libtins 
find_package(libtins REQUIRED)
include_directories(${LIBTINS_INCLUDE_DIRS})
link_libraries(${LIBTINS_LIBRARIES})
add_definitions( -DTINS_STATIC )

# Need to include LibPCAP
## !!! The following won't work because FindPCAP.cmake is not found !!!
# find_package(PCAP REQUIRED)
## !!! The following is an ugly way to include/link libpcap
include_directories("C:/path/to/WpdPack-4.1.2/include")
link_libraries("C:/path/to/WpdPack-4.1.2/Lib/wpcap.lib")
link_libraries("C:/path/to/WpdPack-4.1.2/Lib/Packet.lib")

aux_source_directory(. SRC_LIST)
file (GLOB HDR_LIST "*.h")
add_executable(${PROJECT_NAME} ${SRC_LIST} ${HDR_LIST})
```
Here's how `cmake` is called:
```
Build_SocketListener>cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_PREFIX_PATH=C:\path\to\libtins-3.5_debug_static ..\SocketListener
```

A solution can be to ship `libtins` with a `FindPCAP.cmake` in `CMake` folder :
```
CMake
    - libtinsConfig.cmake
    - libtinsConfigVersion.cmake
    - libtinsTargets.cmake
    - libtinsTargets-debug.cmake
    - FindPCAP.cmake
include
    - tins
lib
    - tins.lib
    - ...
```
and add modify `libtinsConfig.cmake` something as 
```
# - Config file for the libtins package
# It defines the following variables
#  LIBTINS_INCLUDE_DIRS - include directories for libtins
#  LIBTINS_LIBRARIES    - libraries to link against

# Compute paths
get_filename_component(LIBTINS_CMAKE_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
set(LIBTINS_INCLUDE_DIRS "D:/vfomin/MyExamples/cpp/libtins-3.5_source/include")

########### HERE IS THE MODIFICATION ###########
# Include FindPCAP.cmake
LIST(APPEND CMAKE_MODULE_PATH "${LIBTINS_CMAKE_DIR}")
if(WIN32 AND NOT PCAP_ROOT_DIR)
    message(FATAL_ERROR "Please, specify PCAP_ROOT_DIR variable as '-DPCAP_ROOT_DIR=path/to/libpcap'")
endif(WIN32 AND NOT PCAP_ROOT_DIR)
find_package(PCAP REQUIRED)
########### HERE IS THE MODIFICATION ###########

# Our library dependencies (contains definitions for IMPORTED targets)
if(NOT TARGET libtins AND NOT LIBTINS_BINARY_DIR)
    include("${LIBTINS_CMAKE_DIR}/libtinsTargets.cmake")
endif()

# These are IMPORTED targets created by libtinsTargets.cmake
set(LIBTINS_LIBRARIES tins)
```
then it can be more simple to include `libtins` and `libpcap`. Sure, it should be tested on Linux as well...
What do you think about it ?

**Comment by mfontanini** [comment] 2017-05-22 18:22
That would partially work. Note that you can actually disable the use of libpcap in libtins now (so you can just parse and craft packets but not sniff/send them), so requiring libpcap wouldn't be correct. I'll look into this, but this is a good start. Thanks!
